[project]
name = "micro-dao"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.micro-dao-trait]
path = "contracts/micro-dao-trait.clar"
depends_on = ["sip-010-trait-ft-standard"]


[contracts.wmno8]
path = "contracts/wmno8.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.wstx]
path = "contracts/wstx.clar"
depends_on = ["sip-010-trait-ft-standard"]



[contracts.micro-dao]
path = "contracts/micro-dao.clar"
depends_on = ["micro-dao-trait", "sip-010-trait-ft-standard", "wmno8", "wstx"]


[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
