[project]
name = "micro-dao"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.micro-dao-trait]
path = "contracts/micro-dao-trait.clar"
depends_on = []

[contracts.micro-dao]
path = "contracts/micro-dao.clar"
depends_on = ["micro-dao-trait"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
